require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  TargetRailsVersion: 5.0
  TargetRubyVersion: 2.3
  Exclude:
    - 'node_modules/**/*'
    - 'vendor/bundle/**/*'

Layout/AlignHash:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Metrics/AbcSize:
  Max: 23.02

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - 'test/**/*'

Metrics/ClassLength:
  Exclude:
    - 'test/**/*'

Metrics/CyclomaticComplexity:
  Max: 7 # TODO: Lower to 6

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - 'test/**/*'

Metrics/ModuleLength:
  Exclude:
    - 'test/**/*'

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false
