require:
  - rubocop-minitest
  - rubocop-packaging
  - rubocop-performance
  - rubocop-rails
  - rubocop-rake

AllCops:
  TargetRailsVersion: 6.1
  TargetRubyVersion: 3.1
  NewCops: enable
  DisplayStyleGuide: true
  ExtraDetails: true
  Exclude:
    - .git/**/*
    - gemfiles/**/*
    - node_modules/**/*
    - test/generators/tmp/**/*
    - tmp/**/*
    - vendor/**/*

Layout/HashAlignment:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Layout/LineLength:
  Enabled: false

Metrics/AbcSize:
  Max: 23.02

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - 'Rakefile'
    - 'test/**/*'

Metrics/ClassLength:
  Exclude:
    - 'test/**/*'

Metrics/CyclomaticComplexity:
  Max: 7 # TODO: Lower to 6

Metrics/MethodLength:
  Exclude:
    - 'test/**/*'

Metrics/ModuleLength:
  Exclude:
    - 'test/**/*'

Minitest/MultipleAssertions:
  Enabled: false

Rails/RakeEnvironment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false
