AllCops:
  Exclude:
    - 'vendor/bundle/**/*'

Metrics/AbcSize:
  Max: 23.02

Metrics/BlockLength:
  Exclude:
    - '*.gemspec'
    - 'Rakefile'
    - 'test/**/*'

Metrics/ClassLength:
  Exclude:
    - 'test/**/*'

Metrics/CyclomaticComplexity:
  Max: 7 # TODO: Lower to 6

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - 'test/**/*'

Metrics/ModuleLength:
  Exclude:
    - 'test/**/*'

Rails:
  Enabled: true

Style/Documentation:
  Enabled: false

Style/SpaceAroundOperators:
  AllowForAlignment: true
